const users = [
  {
    image: "images/contacts/avatars/cn.png",
    name: "Contact Name",
    pseudo: "Pseudo name",
    email: "E-mailexample@gmail.com",
    phone: "+212 600 00 00 00",
    entreprise: "Company name",
    fonction: "Fonction name",
    poste: "Poste name",
    pays: "Maroc",
  },
  {
    image: "images/contacts/avatars/george.png",
    name: "George Garrett",
    pseudo: "George Garrett",
    email: "anthony.griffin@mail.com",
    phone: "+(478)704-4702",
    entreprise: "Ultricies ultrices vulputate",
    fonction: "Elit augue mauris",
    poste: "condimentum",
    pays: "Austria",
  },
  {
    image: "images/contacts/avatars/bianca.png",
    name: "Bianca Murphy",
    pseudo: "Bianca Murphy",
    email: "adam.freeman@mail.com",
    phone: "+(443)745-1252",
    entreprise: "Gravida neque",
    fonction: "Bibendum mollis",
    poste: "imperdiet",
    pays: "Liechtenstein",
  },
  {
    image: "images/contacts/avatars/chris.png",
    name: "Chris Barrett",
    pseudo: "Chris Barrett",
    email: "walter.alvarado@mail.com",
    phone: "+(349)544-4608",
    entreprise: "Enim tincidunt",
    fonction: "Pharetra consequat",
    poste: "Maximus",
    pays: "Jordan",
  },
  {
    image: "images/contacts/avatars/sara.png",
    name: "Sara McCoy",
    pseudo: "Sara McCoy",
    email: "janet.elliot@mail.com",
    phone: "+(307)742-6250",
    entreprise: "Curabitur enim tincidunt",
    fonction: "Neque pulvinar",
    poste: "Vestibulum",
    pays: "Gambia",
  },
  {
    image: "images/contacts/avatars/denise.png",
    name: "Denise Jordan",
    pseudo: "Denise Jordan",
    email: "anthony.schneider@mail.com",
    phone: "+(194)687-2858",
    entreprise: "Eget vehicula tempor",
    fonction: "Ornare suscipit vulputate",
    poste: "Morbi urna enim",
    pays: "Virgin Islands",
  },
  {
    image: "images/contacts/avatars/george2.png",
    name: "George Garrett",
    pseudo: "George Garrett",
    email: "sara.schneider@mail.com",
    phone: "+(268)268-8236",
    entreprise: "Praesent auctor nulla",
    fonction: "Nisl malesuada maximus",
    poste: "Magna curabitur",
    pays: "Kuwait",
  },
  {
    image: "images/contacts/avatars/charles.png",
    name: "Charles Ramirez",
    pseudo: "Charles Ramirez",
    email: "jasmine.chavez@mail.com",
    phone: "+(548)883-4877",
    entreprise: "Velit interdum",
    fonction: "Tellus vel",
    poste: "Tincidunt",
    pays: "Comoros",
  },
  {
    image: "images/contacts/avatars/anthony.png",
    name: "Anthony Ortiz",
    pseudo: "Anthony Ortiz",
    email: "louis.lynch@mail.com",
    phone: "+(120)807-3511",
    entreprise: "Commodo faucibus",
    fonction: "Dictum vestibulum",
    poste: "tristique",
    pays: "Estonia",
  },
  {
    image: "images/contacts/avatars/jacob.png",
    name: "Jacob Williamson",
    pseudo: "Jacob Williamson",
    email: "richard.estrada@mail.com",
    phone: "+(373)073-3631",
    entreprise: "Convallis lacinia metus",
    fonction: "Non maximus",
    poste: "Fermentum",
    pays: "Bahrain",
  },
];
